;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	objed-beg-of-block
	objed-end-of-block
	objed-kill
	objed-next
	objed-next-line
	objed-next-specialized
	objed-previous
	objed-previous-line
	objed-previous-specialized
	objed-quit
	objed-right-char
	objed-word-object
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-return
	org-self-insert-command
	objed-beg-of-object-at-point
	objed-end-of-object-at-point
	objed-left-char
	objed-right-char
	objed-move-char-backward
	objed-move-char-forward
	objed-move-line-backward
	objed-move-line-forward
	objed-move-object-backward
	objed-move-object-forward
	objed-move-word-backward
	objed-move-word-forward
	objed-forward-symbol
	objed-backward-symbol
	objed-forward-word
	objed-backward-word
	objed--forward-sexp
	objed--backward-sexp
	objed--forward-until
	objed--backward-until
	objed-objed--forward-sexp
	objed-objed--backward-sexp
	objed-objed--backward-until-dispatch
	objed-objed--forward-until-dispatch
	))

(setq mc/cmds-to-run-once
      '(
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-previous-like-this
	))
